### ISSUE TITLE
Primary brand icon

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-style-guide#2]
- Icon for things like favicon, part of logo, etc.
- Icon/Image as part of social presence, like the [Twitter account](https://twitter.com/openspending) and the [GitHub Organisation Page](https://github.com/openspending)

**Comment by smth** [comment]
I have added the primary icon and favicon, plus a large version of each. All can be found [here](https://github.com/openspending/os-style-guide/tree/gh-pages/assets/branding).

**Comment by pwalsh** [comment]
Thanks!
